name: agroecology_map_app
description: "Agroecology Map App"
homepage: "https://agroecologymap.org"
version: 1.0.2

platforms:
  android:

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  http: ^1.2.1
  flutter_map: ^6.1.0
  flutter_map_supercluster: ^5.0.0-dev.1
  latlong2: ^0.9.1
  font_awesome_flutter: ^10.7.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.5
  flutter_login: ^5.0.0
  flutter_secure_storage: ^9.0.0
  http_interceptor: ^2.0.0-beta.8
  dart_countries: ^3.0.3
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  image_picker: ^1.0.7
  flutter_slidable: ^3.1.0
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

funding:
 - https://ko-fi.com/agroecologymap

topics:
 - agroecology
 - permaculture
 - agroforestry
 - citizenscience
 - freesoftware
