name: agroecology_map_app
description: "Agroecology Map App"
homepage: "https://agroecologymap.org"
version: 1.3.5

platforms:
  android:
  ios:

environment:
  sdk: "3.6.2"
  flutter: "3.27.4"

publish_to: none

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dart_countries: ^3.0.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  flutter_login: ^4.2.1
  flutter_map: ^8.2.1
  flutter_map_marker_cluster_plus: ^1.4.2
  flutter_secure_storage: ^9.2.4
  flutter_slidable:
    git:
      url: https://github.com/letsar/flutter_slidable.git
      ref: master
  font_awesome_flutter: ^10.8.0
  geocoding: ^4.0.0
  geolocator: ^13.0.4
  google_fonts: ^6.2.1
  http: ^1.4.0
  http_interceptor: ^2.0.0-beta.8
  image_picker: ^1.1.2
  infinite_scroll_pagination: ^4.0.0
  intl: any
  latlong2: ^0.9.1
  shared_preferences: ^2.3.5
  url_launcher: ^6.3.2
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/logo.png

funding:
  - https://ko-fi.com/agroecologymap

topics:
  - agroecology
  - permaculture
  - agroforestry
  - citizenscience
  - freesoftware
